const assert = require("node:assert");
const fs = require("node:fs");
const path = require("node:path");
const test = require("node:test");

const root = path.resolve(__dirname, "..");
const read = (file) => fs.readFileSync(path.join(root, file), "utf8");

test("mobile product foundation covers the ten H5 capabilities", () => {
  const server = read("server.js");
  const api = read("platform-api.js");
  const library = read("my-stories.html");
  const studio = read("movie-studio.html");
  const studioJs = read("movie-studio.js");
  const app = read("app.html");
  const appJs = read("h5-app.js");
  const chineseStudio = read("chinese-studio.html");
  const manifest = JSON.parse(read("manifest.webmanifest"));
  const worker = read("service-worker.js");
  const renderer = read("ffmpeg-movie-renderer.js");
  const bookExport = read("book-export.js");
  const regionalStorage = read("regional-object-storage.js");
  const launchReadiness = read("launch-readiness.js");
  const launchPage = read("launch-readiness.html");
  const workshop = read("china-workshop.html");

  assert(api.includes("/api/auth/start") && api.includes("/api/auth/verify"), "email and phone OTP endpoints should exist");
  assert(api.includes("/api/auth/wechat"), "WeChat connection point should exist and fail closed until configured");
  assert(api.includes("/api/projects"), "cloud project storage should exist");
  assert(api.includes("/api/media"), "private media upload should exist");
  assert(api.includes("createRegionalObjectStorage") && api.includes("mediaStorage.put") && api.includes("mediaStorage.get"), "private media should use the regional storage adapter");
  assert(["MEDIA_CN", "MEDIA_US", "MEDIA_INTL"].every((token) => regionalStorage.includes(token)), "regional storage should support China, United States and international routes");
  assert(regionalStorage.includes("AWS4-HMAC-SHA256") && regionalStorage.includes("Invalid private-media storage key"), "S3-compatible requests should be signed and storage keys should reject traversal");
  assert(api.includes("MEDIA_REQUIRED_REGIONS") && api.includes("mediaStorage.assertReady"), "production can fail closed when an intended launch region lacks private storage");
  assert(api.includes("ALLOWED_ACCOUNT_REGIONS") && api.includes("configuredRegistrationRegions"), "registration should open only where private regional storage is ready");
  assert(api.includes("BETA_INVITE_CODE_HASHES") && api.includes("betaInviteRedemptions"), "founding beta sign-up should require hashed, capacity-limited regional invitations");
  assert(api.includes("ALLOWED_INTL_COUNTRY_CODES") && api.includes("countryForRegion"), "international sign-up should use an explicit country allowlist");
  assert(api.includes("/api/account") && api.includes("mediaStorage.remove"), "account deletion should remove private media before deleting metadata");
  assert(regionalStorage.includes('createSignedRequest(config, "DELETE"'), "regional object storage should support signed private deletion");
  assert(launchReadiness.includes("ENFORCE_LAUNCH_GATES") && launchReadiness.includes("LEGAL_REVIEW_APPROVED"), "the production launch gate should include technical and human approvals");
  assert(launchPage.includes("data-report") && api.includes("/api/launch-readiness"), "founders should have a secret-free red/green launch status page");
  assert(workshop.includes("chinese-studio.html?workshop=cn") && workshop.includes("classroom-archive.html?new=1&amp;workshop=cn"), "China workshop should expose separate learner and teacher-controlled flows");
  assert(appJs.includes('params.get("workshop") === "cn"') && appJs.includes("作品只保存在这台设备"), "China learner workshop must skip cloud project persistence");
  assert(api.includes("/api/media-usage") && api.includes("MEDIA_ACCOUNT_QUOTA_BYTES") && api.includes("MEDIA_GUEST_QUOTA_BYTES"), "server-side media quotas should prevent unbounded storage cost");
  assert(api.includes("database.media.forEach") && api.includes("media.ownerId = account.id"), "guest media ownership should follow projects into a verified account");
  assert(api.includes("guardianConsents"), "guardian permission records should exist");
  assert(api.includes("api\\/shares"), "invite-only sharing should exist");
  assert(api.includes("/api/orders"), "orders should exist");
  assert(api.includes("/api/product-events"), "activation events should be collected for the founder funnel without story content");
  assert(api.includes("/api/render-jobs"), "movie render plans should exist");
  assert(renderer.includes("ffmpeg-static") && renderer.includes("storieslens-final.mp4") && renderer.includes("seedance-scenes+ffmpeg"), "FFmpeg should privately join approved Seedance scenes without another AI video charge");
  assert(api.includes("outputFilePath: undefined"), "private render filesystem paths should never be returned to the browser");
  assert(studio.includes("data-scene-list") && studioJs.includes("MediaRecorder"), "movie editing and voice recording should be usable in-product");
  assert(studioJs.includes("/export/${format}") && api.includes("export\\/(docx|pdf)"), "authenticated Word and PDF book export should remain in-product");
  assert(bookExport.includes("A5_WIDTH_MM = 148") && bookExport.includes("MARGIN_MM = 18") && bookExport.includes("方正书宋_GBK"), "book export should follow the Lightyear A5 typesetting specification");
  assert(api.includes("/api/print-orders") && studio.includes("data-print-dialog"), "printing and delivery should use a no-charge quote request before collecting a street address");
  assert(api.includes("/api/admin/print-orders") && read("admin-credits.html").includes("data-print-order-list"), "the founder console should expose print quote fulfillment");
  assert(app.includes("data-create-form") && app.includes("data-artwork") && app.includes("data-seed") && app.includes("data-speech"), "formal H5 should begin with artwork, words, or voice");
  assert(app.includes('data-stage="coach"') && app.includes('data-stage="result"'), "formal H5 should keep the three questions and first story page in one flow");
  assert(app.includes('data-stage="mentor-review"') && chineseStudio.includes('data-stage="mentor-review"'), "both solo flows should reveal a visible mentor revision stage after the three questions");
  assert(app.includes("data-revision-confirm") && app.includes("data-revision-read") && appJs.includes("beginMentorReview"), "Yu should require creator confirmation and read-aloud rehearsal for every reviewed sentence");
  assert(appJs.includes('/api/writing-assistant') && appJs.includes('action: "check"'), "the Solo mentor stage should use Yu's trained writing assistant instead of decorative feedback");
  assert(server.includes("minimally corrected version") && server.includes("preserve every story fact"), "sentence review should correct language without ghostwriting the child's story");
  assert(app.includes('data-stage="story-path"') && chineseStudio.includes('data-stage="story-path"'), "both Solo flows should ask for the final form only after the opening setting is complete");
  assert(app.includes('name="story-output" value="book"') && app.includes('name="story-output" value="film"'), "the post-setting decision should offer an illustrated book or story film");
  assert(!chineseStudio.includes('class="chinese-format-picker"') && appJs.includes("showStoryPathStage"), "Chinese creators should not choose an output before Yu helps them finish the first paragraph");
  assert(appJs.includes("outputFormat: selectedOutputFormat") && appJs.includes("updateSettingPreview"), "the selected output and growing setting should persist through the creation flow");
  assert(read("visual-write.html").includes('pageParams.get("output")') && read("visual-write.html").includes("applySelectedOutput"), "the book or film decision should configure the next creation studio instead of being decorative");
  [app, chineseStudio].forEach((studioPage) => {
    assert(studioPage.includes("data-answer-speech"), "every three-question coach should keep voice answering available across the shared question card");
    assert(studioPage.includes("data-read-question") && studioPage.includes("data-auto-read-question"), "every three-question coach should offer manual and automatic question read-aloud");
  });
  assert(app.includes("assets/yu-mascot-logo-v2.png"), "English coaching should show the brand-colored Yu mascot");
  assert(chineseStudio.includes("assets/yu-sage-v1.png"), "Chinese coaching should show its original white-haired Yu story master");
  assert(chineseStudio.includes("data-chinese-idea-entry") && appJs.includes("chineseIdeaEntry"), "Chinese creation should merge typing and speech into one first-class idea entry beside upload");
  assert(app.includes("data-answer-speech-time") && chineseStudio.includes("data-answer-speech-time"), "voice answers should show a visible recording timer in both studios");
  assert(appJs.includes('activeRecognition.continuous = true'), "voice answers should continue through longer child responses");
  assert(appJs.includes('addEventListener("pointerdown"') && appJs.includes('addEventListener("pointerup"'), "voice answers should use press-and-hold interaction");
  assert(appJs.includes('answerSpeechMaxSeconds = 90'), "voice answers should allow up to 90 seconds while remaining bounded");
  assert(appJs.includes("beginAnswerSpeech") && appJs.includes("startAnswerRecognitionCycle") && appJs.includes("answerRecognition"), "press-and-hold voice answering should be wired to the reusable question card for questions one through three");
  assert(appJs.includes("SpeechSynthesisUtterance") && appJs.includes("storieslens_auto_read_questions"), "question read-aloud should use device speech and remember the family's opt-in preference");
  assert(appJs.includes("sageVoiceNames") && appJs.includes('pitch = locale === "zh" ? 0.84'), "Chinese read-aloud should prefer a calm lower-pitched available Mandarin voice");
  const englishStoryLanguage = app.match(/<select data-language[^>]*>[\s\S]*?<\/select>/)?.[0] || "";
  const chineseStoryLanguage = chineseStudio.match(/<select data-language[^>]*>[\s\S]*?<\/select>/)?.[0] || "";
  assert(englishStoryLanguage.includes('value="en"') && !englishStoryLanguage.includes('value="zh"'), "English studio should keep its creation language fixed to English");
  assert(chineseStoryLanguage.includes('value="zh"') && !chineseStoryLanguage.includes('value="en"'), "Chinese studio should keep its creation language fixed to Chinese");
  assert(chineseStudio.includes("data-chinese-idea-entry") && appJs.includes("handleSpeechInput"), "Chinese studio should keep editable speech input within its unified idea entry");
  ["经典小人书", "四格故事", "电影分镜", "data-stage=\"comic-template\""].forEach((token) => assert(chineseStudio.includes(token), `Chinese studio should expose comic template: ${token}`));
  assert(appJs.includes("showComicTemplateStage") && appJs.includes("comicTemplate"), "Comic selection should happen after Yu's three questions and persist into the story profile");
  assert(app.includes("data-chinese-studio-switch"), "English studio should provide one explicit route to the Chinese studio");
  assert(app.includes("Learning Profile｜学习档案") && app.includes("data-map-overall-rit"), "parent flow should offer an optional manual MAP Learning Profile");
  assert(["genre", "craft", "process", "grammar", "mechanics"].every((area) => app.includes(`data-map-low="${area}"`) && app.includes(`data-map-high="${area}"`)), "Learning Profile should accept all five Language Usage area ranges");
  const learningProfileMarkup = app.match(/<details class="learning-profile"[\s\S]*?<\/details>/)?.[0] || "";
  assert(!/<input[^>]+type="file"/i.test(learningProfileMarkup), "Learning Profile must never accept a report upload");
  assert(appJs.includes("parent-manual-entry") && appJs.includes("storieslens_learning_profile"), "Learning Profile should save only structured manual fields on the device");
  assert(appJs.includes("nextThreeGoals") && appJs.includes("fourWeeks") && appJs.includes("storieslens_learning_progress"), "Learning Profile should create a four-week plan scaffold and privacy-minimized progress records");
  assert(appJs.includes("validateLearningProfile") && appJs.includes("low RIT cannot be higher"), "Learning Profile should reject incomplete or invalid RIT ranges");
  assert(read("visual-write.html").includes("getMapLearningContext") && read("visual-write.html").includes("mapInstructionalArea"), "Yu should receive the optional Learning Profile during coaching");
  assert(appJs.includes("coach_question_answered") && appJs.includes("first_story_page_created"), "formal H5 should measure its activation moment");
  assert(app.includes('src="artwork-upload-safety.js?') && appJs.includes("StoriesLensArtworkSafety.processArtwork"), "formal H5 should privacy-review artwork before it can be stored");
  assert(api.includes("reviewArtworkSafety(body.dataUrl)") && api.includes("containsRealPerson") && !api.includes("Real-person photos are not stored"), "private media API should accept safety-reviewed real-person photos and label them server-side");
  assert(app.includes("Personal photos may become a private book or video") && chineseStudio.includes("真人照片可以用于制作私密故事书或视频"), "private beta studios should clearly accept consented personal photos for books and videos");
  assert(app.includes("data-photo-consent-processing") && chineseStudio.includes("data-photo-consent-processing"), "both studios should disclose regional cloud processing before personal-photo consent");
  assert(api.includes('"regional_ai_processing"') && api.includes("acknowledgedRegionalProcessing"), "personal-photo consent must explicitly cover regional safety and AI processing");
  assert(api.includes("personalPhotoMediaDeleted") && api.includes('searchParams.get("permanent") === "true"'), "revocation and permanent project deletion should remove stored personal-photo media");
  assert(!appJs.includes("工作坊仅接收画作，不接收真人照片") && appJs.includes("真人照片安全检查通过"), "a safe real-person photo should continue into private cloud creation instead of being blocked");
  assert(appJs.includes("safeArtwork.review?.checks?.realPerson") && appJs.includes("personalPhoto"), "personal photos should be classified explicitly without making a face itself a rejection reason");
  assert(appJs.includes('platform.api("/api/projects"') && appJs.includes('platform.api("/api/media"'), "formal H5 should save real private projects and artwork");
  assert(appJs.includes("persistApprovedArtwork") && appJs.includes("Safety check passed. Saving to your private library"), "approved mobile artwork should be persisted immediately instead of waiting for the three-question flow");
  assert(appJs.includes('from: "h5"'), "formal H5 should continue directly into the guided creation path");
  assert(read("squad-board.html").includes("data-create-and-generate") && read("squad-board.html").includes("data-visual-candidate"), "squad owners should generate a visual anchor beside the character lock and every creator should review candidates before saving");
  assert(read("squad-board.js").includes("acceptPendingVisual") && read("squad-board.html").includes("Not yet—regenerate"), "squad image generation should debit each attempt but attach only the creator-approved candidate");
  assert(api.includes("visual-anchor") && api.includes("SQUAD_ANCHOR_OWNER_REQUIRED"), "only the squad owner should be able to lock the shared visual anchor");
  assert(read("my-stories.js").includes("project-report.html?project=") && read("project-report.html").includes("data-book-grid"), "every saved project should open a visible growth report and one-book reading path");
  assert(api.includes("projectReports") && api.includes("createGrowthReport"), "growth reports should be owner-only persisted project records");
  assert(read("project-report.js").includes("book.coverUrl") && read("project-report.js").includes("book.reason"), "each recommendation should show a verified cover and a project-specific reason");
  assert(library.includes("Save across devices") && library.includes("GUARDIAN APPROVAL"), "the mobile library should expose account and privacy controls");
  assert(library.includes("data-primary-region") && ["cn", "us", "intl"].every((region) => library.includes(`value="${region}"`)), "account signup should require one of the three global service regions");
  assert(library.includes("data-storage-meter") && read("my-stories.js").includes("/api/media-usage"), "account page should explain private storage usage without cloud jargon");
  assert(read("my-stories.js").includes("registrationRegions") && read("my-stories.js").includes("option.disabled"), "unopened regions should be visibly unavailable during a staged pilot");
  assert(api.includes("regionProfile") && api.includes("regionConsentVersion") && api.includes("regionConfirmedAt"), "the account should persist an explicit region decision and consent version");
  assert(api.includes('aiProviderRoute: "china"') && api.includes('aiProviderRoute: "us"') && api.includes('aiProviderRoute: "international"'), "the backend should keep provider-neutral regional AI routes");
  assert(library.includes("never change it from your IP alone") && !api.includes("cf-ipcountry"), "IP geolocation must not silently choose a data region");
  assert.strictEqual(manifest.display, "standalone", "PWA should install in standalone mode");
  assert.strictEqual(manifest.start_url, "/app.html?source=pwa", "installed PWA should open the formal H5 product");
  assert(worker.includes("/api/") && worker.includes("offline.html"), "service worker should preserve offline pages without caching private APIs");
  assert(server.includes("microphone=(self)"), "first-party recording should be permitted");
});

test("private story renderer uses textContent instead of injected HTML", () => {
  const renderer = read("shared-story.js");
  assert(renderer.includes("textContent"));
  assert(!renderer.includes("innerHTML"));
});
